# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/BaseDCaTx/CLionProjects/xhttp-revised

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/BaseDCaTx/CLionProjects/xhttp-revised

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/BaseDCaTx/CLionProjects/xhttp-revised/CMakeFiles /mnt/c/Users/BaseDCaTx/CLionProjects/xhttp-revised//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/BaseDCaTx/CLionProjects/xhttp-revised/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xhttp_c

# Build rule for target.
xhttp_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xhttp_c
.PHONY : xhttp_c

# fast build rule for target.
xhttp_c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/build
.PHONY : xhttp_c/fast

#=============================================================================
# Target rules for targets named xhttp_s

# Build rule for target.
xhttp_s: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xhttp_s
.PHONY : xhttp_s

# fast build rule for target.
xhttp_s/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/build
.PHONY : xhttp_s/fast

client/Client.o: client/Client.cpp.o
.PHONY : client/Client.o

# target to build an object file
client/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/client/Client.cpp.o
.PHONY : client/Client.cpp.o

client/Client.i: client/Client.cpp.i
.PHONY : client/Client.i

# target to preprocess a source file
client/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/client/Client.cpp.i
.PHONY : client/Client.cpp.i

client/Client.s: client/Client.cpp.s
.PHONY : client/Client.s

# target to generate assembly for a file
client/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/client/Client.cpp.s
.PHONY : client/Client.cpp.s

logger/Logger.o: logger/Logger.cpp.o
.PHONY : logger/Logger.o

# target to build an object file
logger/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/logger/Logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/logger/Logger.cpp.o
.PHONY : logger/Logger.cpp.o

logger/Logger.i: logger/Logger.cpp.i
.PHONY : logger/Logger.i

# target to preprocess a source file
logger/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/logger/Logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/logger/Logger.cpp.i
.PHONY : logger/Logger.cpp.i

logger/Logger.s: logger/Logger.cpp.s
.PHONY : logger/Logger.s

# target to generate assembly for a file
logger/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/logger/Logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/logger/Logger.cpp.s
.PHONY : logger/Logger.cpp.s

server/Server.o: server/Server.cpp.o
.PHONY : server/Server.o

# target to build an object file
server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/server/Server.cpp.o
.PHONY : server/Server.cpp.o

server/Server.i: server/Server.cpp.i
.PHONY : server/Server.i

# target to preprocess a source file
server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/server/Server.cpp.i
.PHONY : server/Server.cpp.i

server/Server.s: server/Server.cpp.s
.PHONY : server/Server.s

# target to generate assembly for a file
server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/server/Server.cpp.s
.PHONY : server/Server.cpp.s

utils/Utils.o: utils/Utils.cpp.o
.PHONY : utils/Utils.o

# target to build an object file
utils/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/utils/Utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/utils/Utils.cpp.o
.PHONY : utils/Utils.cpp.o

utils/Utils.i: utils/Utils.cpp.i
.PHONY : utils/Utils.i

# target to preprocess a source file
utils/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/utils/Utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/utils/Utils.cpp.i
.PHONY : utils/Utils.cpp.i

utils/Utils.s: utils/Utils.cpp.s
.PHONY : utils/Utils.s

# target to generate assembly for a file
utils/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_c.dir/build.make CMakeFiles/xhttp_c.dir/utils/Utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xhttp_s.dir/build.make CMakeFiles/xhttp_s.dir/utils/Utils.cpp.s
.PHONY : utils/Utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xhttp_c"
	@echo "... xhttp_s"
	@echo "... client/Client.o"
	@echo "... client/Client.i"
	@echo "... client/Client.s"
	@echo "... logger/Logger.o"
	@echo "... logger/Logger.i"
	@echo "... logger/Logger.s"
	@echo "... server/Server.o"
	@echo "... server/Server.i"
	@echo "... server/Server.s"
	@echo "... utils/Utils.o"
	@echo "... utils/Utils.i"
	@echo "... utils/Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

